#!/bin/bash

# List all files in the current directory
echo "Current Directory:"
ls -la

# List all files in the parent directory
echo "Parent Directory:"
ls -la ..

# List all files in the /boot directory
echo "/boot Directory:"
ls -la /boot
